# Generated by Django 2.2.6 on 2019-12-05 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroCompras',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compras', models.CharField(max_length=10)),
                ('fecha', models.DateField()),
            ],
        ),
    ]
