# Generated by Django 2.2.6 on 2019-12-05 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroUsuarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('users', models.CharField(max_length=10)),
                ('fecha', models.DateField()),
            ],
            options={
                'verbose_name_plural': 'Registros de Usuarios',
            },
        ),
        migrations.AlterModelOptions(
            name='registrocompras',
            options={'verbose_name_plural': 'Registros de Compras'},
        ),
    ]
