# Generated by Django 2.2.6 on 2019-12-05 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20191205_1327'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroSurferos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('users', models.CharField(max_length=10)),
                ('fecha', models.DateField()),
            ],
            options={
                'verbose_name_plural': 'Registros de Surferos',
            },
        ),
        migrations.RenameModel(
            old_name='RegistroUsuarios',
            new_name='RegistroFotografos',
        ),
        migrations.AlterModelOptions(
            name='registrofotografos',
            options={'verbose_name_plural': 'Registros de Fotografos'},
        ),
    ]
