# Generated by Django 2.1.9 on 2019-08-08 11:09

from django.db import migrations, models
import django.db.models.deletion
import kradleco.apps.landing.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alquiler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(blank=True, default='', max_length=50)),
                ('euros_dia', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('euros_semana', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('euros_mes', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=100)),
                ('ref', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=500)),
                ('pvp', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8)),
                ('precio_coste', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8)),
                ('precio_comparacion', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8)),
                ('imagen_principal', models.ImageField(blank=True, upload_to=kradleco.apps.landing.models.upload_to_articulos)),
                ('stock', models.IntegerField(blank=True, default=0)),
                ('marca', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'verbose_name_plural': 'Artículos',
            },
        ),
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=15, null=True)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('total_iva', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('pago_ok', models.BooleanField(blank=True, default=False)),
            ],
        ),
        migrations.CreateModel(
            name='CarritoItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(blank=True, default=1)),
                ('precio_final', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Coleccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Coleccion', max_length=50)),
                ('visible', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Conexion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ACEPTADA', 'Aceptada'), ('CANCELADA', 'Cancelada')], default='PENDIENTE', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='DefinicionVariante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Espacio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_distribuidor', models.BooleanField(blank=True, default=False)),
                ('is_propia_marca', models.BooleanField(blank=True, default=False)),
                ('is_propietario', models.BooleanField(blank=True, default=False)),
                ('is_nuevo', models.BooleanField(blank=True, default=False)),
                ('direccion', models.CharField(blank=True, default='', max_length=50)),
                ('tags', models.CharField(blank=True, default='', max_length=50)),
                ('precio_dia', models.IntegerField(blank=True, default=0)),
                ('precio_semana', models.IntegerField(blank=True, default=0)),
                ('precio_mes', models.IntegerField(blank=True, default=0)),
                ('tiempo_minimo', models.CharField(default='', max_length=50)),
                ('metros_disponibles', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('ventas', models.IntegerField(blank=True, default=0)),
                ('negociable', models.BooleanField(blank=True, default=False)),
            ],
        ),
        migrations.CreateModel(
            name='EstiloVida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estilo', models.CharField(choices=[('ECOLOGICO', 'Nature/Ecológico/Medio-ambiente'), ('CLASICO', 'Conservador/Clásico'), ('AVENTURERO', 'Riesgo/Avengura/Viajero'), ('SPORT', 'Fitness/Sport'), ('BOHEMIO', 'Bohemio')], default='CLASICO', max_length=35)),
            ],
            options={
                'verbose_name_plural': 'Estilo',
            },
        ),
        migrations.CreateModel(
            name='GaleriaArticulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, upload_to=kradleco.apps.landing.models.upload_to_articulos)),
            ],
        ),
        migrations.CreateModel(
            name='Maestro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_online', models.BooleanField(blank=True, default=False)),
                ('is_mayorista', models.BooleanField(blank=True, default=False)),
                ('is_marketplaces', models.BooleanField(blank=True, default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Mercado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mercado', models.CharField(choices=[('TEXTIL', 'Textil'), ('CALZADO', 'Calzado'), ('COMPLEMENTOS', 'Complementos'), ('MAQUILLAJE', 'Maquillaje'), ('COSMETICA', 'Cosmética'), ('PERFUMERIA', 'Perfumería'), ('OTRO', 'Otro')], default='TEXTIL', max_length=15)),
            ],
            options={
                'verbose_name_plural': 'Mercado',
            },
        ),
        migrations.CreateModel(
            name='Promocion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(blank=True, max_length=100)),
                ('nombre', models.CharField(blank=True, max_length=30)),
                ('canjeos', models.IntegerField(blank=True, default=0)),
                ('automatica', models.BooleanField(default=False)),
                ('codigo', models.BooleanField(default=False)),
                ('codigo_value', models.SlugField(blank=True, max_length=15, null=True, unique=True)),
                ('tipo', models.CharField(choices=[('RBJ', 'Rebaja'), ('PER', 'Personalizada')], default='RBJ', max_length=15)),
                ('requisito', models.CharField(choices=[('', '-Sin requisito-'), ('EUR', 'Euros'), ('UD', 'Unidades')], default='', max_length=15)),
                ('requisito_value', models.IntegerField(blank=True, null=True)),
                ('recompensa', models.CharField(choices=[('', '-Sin requisito-'), ('EUR', 'Euros'), ('UD', 'Unidades'), ('PCT', 'Porcentaje')], default='', max_length=15)),
                ('recompensa_value', models.IntegerField(blank=True, null=True)),
                ('recompensa_unidades', models.IntegerField(blank=True, null=True)),
                ('limite', models.CharField(choices=[('EXS', 'Existencias'), ('CLI', 'Clientes')], default='EXS', max_length=15)),
                ('limite_value', models.IntegerField(blank=True, null=True)),
                ('fecha_desde', models.DateField(blank=True, null=True)),
                ('fecha_hasta', models.DateField(blank=True, null=True)),
                ('visible', models.BooleanField(blank=True, default=True)),
            ],
        ),
        migrations.CreateModel(
            name='PropuestaComercial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='propuesta', max_length=25)),
                ('fecha_desde', models.DateField()),
                ('fecha_hasta', models.DateField()),
                ('precio_dia', models.FloatField()),
                ('precio_semana', models.FloatField(default=0)),
                ('precio_mes', models.FloatField(default=0)),
                ('precio_total', models.FloatField(blank=True, default=0)),
                ('porcentaje_ventas', models.FloatField()),
                ('is_acepta_propuestos', models.BooleanField(blank=True, default=False)),
                ('precio_dia_propuesto', models.FloatField(blank=True, default=0.0)),
                ('precio_semana_propuesto', models.FloatField(blank=True, default=0.0)),
                ('precio_mes_propuesto', models.FloatField(blank=True, default=0.0)),
                ('precio_total_propuesto', models.FloatField(default=0)),
                ('porcentaje_ventas_propuesto', models.FloatField(default=0)),
                ('politica_cancelacion_m', models.CharField(choices=[('LEVE', 'Leve'), ('ESTRICTA', 'Estricta')], default='LEVE', max_length=15)),
                ('politica_cancelacion_e', models.CharField(choices=[('LEVE', 'Leve'), ('ESTRICTA', 'Estricta')], default='LEVE', max_length=15)),
                ('metros_cuadrados', models.FloatField(blank=True, default=0.0, null=True)),
                ('is_necesita_mobiliario', models.BooleanField(default=False)),
                ('comentarios', models.CharField(default='', max_length=100)),
                ('is_cancelada', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Servicios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servicios', models.CharField(choices=[('FABRICACION', 'Fabricación, Confección, Packaging'), ('OBRAS', 'Obras, Logística, Almacén'), ('SOFTWARE', 'Software, Hardware, Comunicaciones'), ('GESTORIAS', 'Gestorías, Seguros, Abogados'), ('FINANCIACION', 'Financiación, Bancos'), ('MARKETING', 'Marketing, Eventos'), ('INFLUENCERS', 'Influencers, Ventas'), ('CONSULTORIA', 'Consultoría, Asesoramiento'), ('ASOCIACIONES', 'Asociaciones, Instituciones'), ('INFORMACION', 'Información, Noticias')], default='FABRICACION', max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Servicios',
            },
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quien_eres', models.CharField(choices=[('MARCA', 'Marca'), ('ESPACIO', 'Espacios (Offline/Online)'), ('SERVICIO', 'Servicio')], default='MARCA', max_length=10)),
                ('que_buscas', models.CharField(choices=[('MARCA', 'Marca'), ('ESPACIO', 'Espacios (Offline/Online)'), ('SERVICIO', 'Servicio')], default='ESPACIO', max_length=10)),
                ('email', models.EmailField(max_length=80)),
                ('nombre', models.CharField(max_length=100)),
                ('estilo', models.ManyToManyField(to='landing.EstiloVida')),
                ('mercado', models.ManyToManyField(to='landing.Mercado')),
                ('servicios', models.ManyToManyField(to='landing.Servicios')),
            ],
            options={
                'verbose_name_plural': 'Solicitudes',
            },
        ),
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.CharField(choices=[('MUJER', 'Mujer'), ('HOMBRE', 'Hombre'), ('NIÑOS', 'Niños'), ('ADOLESCENTES', 'Adolescentes'), ('ADULTOS', 'Adultos')], default='MUJER', max_length=15)),
            ],
            options={
                'verbose_name_plural': 'Target',
            },
        ),
        migrations.CreateModel(
            name='VarianteArticulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opcion_1', models.CharField(blank=True, max_length=15, null=True)),
                ('opcion_1_value', models.CharField(blank=True, max_length=15, null=True)),
                ('opcion_2', models.CharField(blank=True, max_length=15, null=True)),
                ('opcion_2_value', models.CharField(blank=True, max_length=15, null=True)),
                ('opcion_3', models.CharField(blank=True, max_length=15, null=True)),
                ('opcion_3_value', models.CharField(blank=True, max_length=15, null=True)),
                ('url', models.CharField(max_length=100)),
                ('ref', models.CharField(max_length=100)),
                ('pvp', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8)),
                ('precio_coste', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8)),
                ('precio_comparacion', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8)),
                ('imagen_principal', models.ImageField(blank=True, upload_to=kradleco.apps.landing.models.upload_to_articulos)),
                ('stock', models.IntegerField(blank=True, default=0)),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landing.Articulo')),
            ],
        ),
        migrations.AddField(
            model_name='solicitud',
            name='target',
            field=models.ManyToManyField(to='landing.Target'),
        ),
    ]
