# Generated by Django 2.1.9 on 2019-08-08 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_auto_20190808_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocion',
            name='articulos_obtiene',
            field=models.ManyToManyField(blank=True, related_name='promocionados', to='landing.Articulo'),
        ),
    ]
