# Generated by Django 2.1.9 on 2019-08-09 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0003_auto_20190808_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrito',
            name='items_promo',
            field=models.ManyToManyField(blank=True, related_name='en_carrito_y_promocion', to='landing.CarritoItem'),
        ),
    ]
