# Generated by Django 2.1.9 on 2019-08-21 13:15

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0005_carritoitem_precio_original'),
    ]

    operations = [
        migrations.CreateModel(
            name='PuntoDeVenta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='punto de venta', max_length=50)),
                ('fecha_inicio', models.DateField(blank=True, default=django.utils.timezone.now)),
            ],
        ),
        migrations.AddField(
            model_name='propuestacomercial',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PREACEPTADA', 'Preaceptada'), ('CANCELADA', 'Cancelada')], default='PENDIENTE', max_length=15),
        ),
        migrations.AlterField(
            model_name='propuestacomercial',
            name='precio_dia',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='propuestacomercial',
            name='precio_dia_propuesto',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='propuestacomercial',
            name='precio_mes',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='propuestacomercial',
            name='precio_mes_propuesto',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='propuestacomercial',
            name='precio_semana',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='propuestacomercial',
            name='precio_semana_propuesto',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='propuestacomercial',
            name='precio_total_propuesto',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='puntodeventa',
            name='propuesta',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='propuesta', to='landing.PropuestaComercial'),
        ),
    ]
