# Generated by Django 2.1.9 on 2019-08-23 08:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('landing', '0006_auto_20190821_1515'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pago_ok', models.BooleanField(default=False)),
                ('fecha', models.DateTimeField(auto_now_add=True, null=True)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('items', models.ManyToManyField(related_name='en_pedido', to='landing.CarritoItem')),
                ('items_promo', models.ManyToManyField(related_name='en_pedido_y_promo', to='landing.CarritoItem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='galeriaarticulo',
            name='articulo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='galeria', to='landing.Articulo'),
        ),
        migrations.AlterField(
            model_name='propuestacomercial',
            name='nombre',
            field=models.CharField(default='propuesta', max_length=75),
        ),
        migrations.AlterField(
            model_name='variantearticulo',
            name='articulo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variantearticulo', to='landing.Articulo'),
        ),
    ]
