# Generated by Django 2.1.9 on 2019-08-23 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0007_auto_20190823_1052'),
    ]

    operations = [
        migrations.AddField(
            model_name='puntodeventa',
            name='colecciones',
            field=models.ManyToManyField(blank=True, to='landing.Coleccion'),
        ),
    ]
