# Generated by Django 2.1.9 on 2019-08-23 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0008_puntodeventa_colecciones'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticuloPDV',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=0)),
                ('articulo', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='en_pdv', to='landing.Articulo')),
                ('pdv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articulos', to='landing.PuntoDeVenta')),
                ('variante', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='en_pdv', to='landing.VarianteArticulo')),
            ],
        ),
    ]
