# Generated by Django 2.1.9 on 2019-08-26 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0009_articulopdv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulopdv',
            name='articulo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='en_pdv', to='landing.Articulo'),
        ),
        migrations.AlterField(
            model_name='articulopdv',
            name='variante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='en_pdv', to='landing.VarianteArticulo'),
        ),
    ]
