# Generated by Django 2.1.9 on 2019-08-26 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0010_auto_20190826_1052'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulopdv',
            name='coleccion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='coleccion_en_pdv', to='landing.Coleccion'),
            preserve_default=False,
        ),
    ]
