# Generated by Django 2.1.9 on 2019-08-28 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0012_marca_direccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='codigo',
            field=models.SlugField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='items_promo',
            field=models.ManyToManyField(blank=True, related_name='en_pedido_y_promo', to='landing.CarritoItem'),
        ),
    ]
