# Generated by Django 2.1.9 on 2019-08-28 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0013_auto_20190828_1007'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='medio',
            field=models.CharField(choices=[('TPV', 'TPV móvil'), ('TF', 'Terminal físico'), ('EF', 'Efectivo')], default='TPV', max_length=15),
        ),
    ]
