# Generated by Django 2.1.9 on 2019-08-28 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0015_pedido_pdv'),
    ]

    operations = [
        migrations.AddField(
            model_name='carritoitem',
            name='pdv',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items_carrito', to='landing.PuntoDeVenta'),
        ),
    ]
