# Generated by Django 2.1.9 on 2019-08-29 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0016_carritoitem_pdv'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alquiler',
            options={'verbose_name_plural': 'Alquileres'},
        ),
        migrations.AlterModelOptions(
            name='coleccion',
            options={'verbose_name_plural': 'Colecciones'},
        ),
        migrations.AlterModelOptions(
            name='conexion',
            options={'verbose_name_plural': 'Conexiones'},
        ),
        migrations.AlterModelOptions(
            name='promocion',
            options={'verbose_name_plural': 'Promociones'},
        ),
        migrations.AlterModelOptions(
            name='propuestacomercial',
            options={'verbose_name_plural': 'Propuestas Comerciales'},
        ),
        migrations.AlterModelOptions(
            name='puntodeventa',
            options={'verbose_name_plural': 'Puntos de Venta'},
        ),
        migrations.AlterField(
            model_name='estilovida',
            name='estilo',
            field=models.CharField(choices=[('ECOLOGICO', 'Nature/Ecológico/Medio-ambiente'), ('CLASICO', 'Conservador/Clásico'), ('AVENTURERO', 'Riesgo/Avengura/Viajero'), ('SPORT', 'Fitness/Sport'), ('BOHEMIO', 'Bohemio')], default='ECOLOGICO', max_length=35),
        ),
    ]
