# Generated by Django 2.1.9 on 2019-09-02 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0017_auto_20190829_1445'),
        ('landing', '0017_auto_20190830_1351'),
    ]

    operations = [
    ]
