# Generated by Django 2.1.9 on 2019-09-05 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0019_puntodeventa_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='propuestacomercial',
            name='modificaciones_receptor',
            field=models.IntegerField(default=0),
        ),
    ]
