# Generated by Django 2.1.9 on 2019-09-06 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0020_propuestacomercial_modificaciones_receptor'),
    ]

    operations = [
        migrations.AddField(
            model_name='puntodeventa',
            name='validado_espacio',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='puntodeventa',
            name='validado_marca',
            field=models.BooleanField(default=False),
        ),
    ]
