# Generated by Django 2.1.9 on 2019-09-09 10:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('landing', '0022_notificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacion',
            name='emisor',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificacion_emisor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='estado',
            field=models.CharField(choices=[('PRECIOS', 'Precios'), ('ENVIOS', 'Envios')], default='PRECIOS', max_length=15),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='receptor',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificacion_receptor', to=settings.AUTH_USER_MODEL),
        ),
    ]
