# Generated by Django 2.1.9 on 2019-09-10 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0023_auto_20190909_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='handle',
            field=models.CharField(blank=True, default='-', max_length=20, null=True),
        ),
    ]
