# Generated by Django 2.1.9 on 2019-08-08 11:09

from django.conf import settings
import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import kradleco.apps.users.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('tipo_de_usuario', models.CharField(choices=[('KRADELER', 'Kradeler'), ('SUPPORTER', 'Supporter'), ('ADMIN', 'Admin')], default='KRADELER', max_length=15)),
                ('telefono', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Formato: '+999999999'. Max 15 dígitos.", regex='^\\+?1?\\d{9,15}$')])),
                ('is_empresa', models.BooleanField(blank=True, default=False)),
                ('is_autonomo', models.BooleanField(blank=True, default=False)),
                ('is_marca', models.BooleanField(blank=True, default=False)),
                ('is_espacio', models.BooleanField(blank=True, default=False)),
                ('titular', models.CharField(default='', max_length=50)),
                ('sobre_mi_negocio', models.CharField(default='', max_length=500)),
                ('logo', models.ImageField(blank=True, default='', null=True, storage=kradleco.apps.users.models.OverwriteStorage(), upload_to=kradleco.apps.users.models.upload_to_logo)),
                ('foto_perfil', models.ImageField(blank=True, null=True, storage=kradleco.apps.users.models.OverwriteStorage(), upload_to=kradleco.apps.users.models.upload_to_perfil)),
                ('facebook', models.URLField(blank=True, default='')),
                ('linkedin', models.URLField(blank=True, default='')),
                ('youtube', models.URLField(blank=True, default='')),
                ('twitter', models.URLField(blank=True, default='')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Autonomo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razon_social', models.CharField(max_length=60)),
                ('nif', models.CharField(blank=True, max_length=25)),
                ('antiguedad', models.CharField(blank=True, choices=[('', 'Antigüedad'), ('1año', 'menos de 1 año'), ('1a2años', '1-2 años'), ('2a5años', '2-5 años'), ('5años', 'más de 5 años')], default='1año', max_length=50)),
                ('facturacion', models.CharField(blank=True, choices=[('', 'Rango de facturación mensual'), ('NoFacturado', 'Aún no he facturado'), ('0-5000', '0€ - 5.000€'), ('5000-20000', '5.000€ - 20.000€'), ('20000-100000', '20.000€ - 100.000€'), ('100000', 'más de 100.000€')], default='NoFacturado', max_length=50)),
                ('irpf', models.CharField(blank=True, max_length=25)),
                ('iva', models.CharField(blank=True, max_length=15)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='autonomo', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntuacion', models.FloatField(blank=True, default=5)),
                ('contenido', models.TextField()),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='autor', to=settings.AUTH_USER_MODEL)),
                ('para', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='para_mi', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razon_social', models.CharField(max_length=60)),
                ('nif', models.CharField(blank=True, max_length=25)),
                ('antiguedad', models.CharField(blank=True, choices=[('', 'Antigüedad'), ('1año', 'menos de 1 año'), ('1a2años', '1-2 años'), ('2a5años', '2-5 años'), ('5años', 'más de 5 años')], default='1año', max_length=50)),
                ('facturacion', models.CharField(blank=True, choices=[('', 'Rango de facturación mensual'), ('NoFacturado', 'Aún no he facturado'), ('0-5000', '0€ - 5.000€'), ('5000-20000', '5.000€ - 20.000€'), ('20000-100000', '20.000€ - 100.000€'), ('100000', 'más de 100.000€')], default='NoFacturado', max_length=50)),
                ('iva', models.CharField(blank=True, max_length=15)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empresa', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GaleriaUsuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, upload_to='img/galeria/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='galeria', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MiPerfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(blank=True, default='', max_length=100)),
                ('cp', models.CharField(blank=True, default='', max_length=8)),
                ('ciudad', models.CharField(blank=True, default='', max_length=20)),
                ('pais', models.CharField(blank=True, default='', max_length=20)),
                ('ventas', models.IntegerField(default=0)),
                ('negociable', models.BooleanField(default=False)),
                ('is_marca', models.BooleanField(default=False)),
                ('is_espacio', models.BooleanField(default=False)),
                ('puntuacion', models.FloatField(blank=True, default=0)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lng', models.FloatField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Perfiles',
            },
        ),
    ]
