# Generated by Django 2.1.9 on 2019-09-16 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='tipo_de_usuario',
            field=models.CharField(choices=[('SURFERO', 'Kradeler'), ('FOTOGRAFO', 'Supporter'), ('ADMIN', 'Admin')], default='SURFERO', max_length=15),
        ),
    ]
