# Generated by Django 2.1.9 on 2019-09-19 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_direccion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='direccion',
            new_name='pais',
        ),
        migrations.AddField(
            model_name='customuser',
            name='zona',
            field=models.CharField(default='', max_length=50),
        ),
    ]
