# Generated by Django 2.1.9 on 2019-09-20 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20190919_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='CV',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='alias',
            field=models.BooleanField(default='', null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='main_pic',
            field=models.ImageField(blank=True, upload_to='img/photographer/'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to='img/photographer/'),
        ),
    ]
