# Generated by Django 2.1.9 on 2019-09-20 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20190920_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='alias',
            field=models.TextField(default='', null=True),
        ),
    ]
