# Generated by Django 2.1.9 on 2019-10-02 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20190920_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='alias',
            field=models.CharField(default='', max_length=25, null=True),
        ),
    ]
