# Generated by Django 2.1.9 on 2019-10-03 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20191002_1350'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autonomo',
            name='user',
        ),
        migrations.RemoveField(
            model_name='comentario',
            name='autor',
        ),
        migrations.RemoveField(
            model_name='comentario',
            name='para',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='user',
        ),
        migrations.RemoveField(
            model_name='galeriausuario',
            name='user',
        ),
        migrations.RemoveField(
            model_name='miperfil',
            name='user',
        ),
        migrations.DeleteModel(
            name='Autonomo',
        ),
        migrations.DeleteModel(
            name='Comentario',
        ),
        migrations.DeleteModel(
            name='Empresa',
        ),
        migrations.DeleteModel(
            name='GaleriaUsuario',
        ),
        migrations.DeleteModel(
            name='MiPerfil',
        ),
    ]
