# Generated by Django 2.2.6 on 2019-10-08 15:02

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_customuser_wishlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='wishlist',
            field=models.CharField(default='', max_length=500, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')]),
        ),
    ]
