# Generated by Django 2.1.9 on 2019-10-21 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20191008_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='zona',
            field=models.CharField(choices=[('EU', 'Europe'), ('AF', 'Africa'), ('AS', 'Asia'), ('OC', 'Oceania'), ('NA', 'North America'), ('SA', 'South America')], default='EU', max_length=50),
        ),
    ]
