# Generated by Django 2.1.9 on 2019-10-21 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20191021_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='CV',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='alias',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
    ]
