# Generated by Django 2.1.9 on 2019-10-22 08:35

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20191021_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='wishlist',
            field=models.CharField(blank=True, default='', max_length=500, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')]),
        ),
    ]
