# Generated by Django 2.1.9 on 2019-12-26 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_stripeuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='tipo_de_usuario',
            field=models.CharField(choices=[('UNASIGNED', 'UNASIGNED'), ('SURFERO', 'Surfero'), ('FOTOGRAFO', 'Fotografo'), ('ADMIN', 'Admin')], default='SURFERO', max_length=15),
        ),
    ]
