# Generated by Django 2.1.9 on 2020-01-03 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_auto_20200103_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='stripe_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
