# Generated by Django 2.1.9 on 2020-04-21 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_auto_20200103_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='zona',
            field=models.CharField(choices=[('Europe', 'Europe'), ('Africa', 'Africa'), ('Asia', 'Asia'), ('Oceania', 'Oceania'), ('North America', 'North America'), ('South America', 'South America')], max_length=50),
        ),
    ]
