# Generated by Django 2.1.9 on 2020-06-03 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_auto_20200421_1104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='zona',
        ),
    ]
