# Generated by Django 2.1.9 on 2020-06-23 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_remove_customuser_zona'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Continente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('Europe', 'Europe'), ('Africa', 'Africa'), ('Asia', 'Asia'), ('Oceania', 'Oceania'), ('North America', 'North America'), ('South America', 'South America')], default='Europa', max_length=25)),
            ],
            options={
                'verbose_name': 'Continente',
            },
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25)),
                ('continente', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='pais', to='users.Continente')),
            ],
            options={
                'verbose_name_plural': 'Paises',
                'verbose_name': 'Pais',
            },
        ),
        migrations.CreateModel(
            name='Spot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25)),
                ('area', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='spot', to='users.Area')),
            ],
        ),
        migrations.AlterField(
            model_name='customuser',
            name='pais',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='u_pais', to='users.Pais'),
        ),
        migrations.AddField(
            model_name='area',
            name='pais',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='area', to='users.Pais'),
        ),
    ]
