# Generated by Django 2.1.9 on 2020-06-23 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_remove_customuser_zona'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='pais',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='u_pais', to='home.Pais'),
        ),
    ]
