# Generated by Django 2.1.9 on 2020-06-23 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0048_auto_20200623_1553'),
        ('users', '0027_auto_20200623_1047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='area',
            name='pais',
        ),
        migrations.RemoveField(
            model_name='pais',
            name='continente',
        ),
        migrations.RemoveField(
            model_name='spot',
            name='area',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='pais',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='u_pais', to='home.Pais'),
        ),
        migrations.DeleteModel(
            name='Area',
        ),
        migrations.DeleteModel(
            name='Continente',
        ),
        migrations.DeleteModel(
            name='Pais',
        ),
        migrations.DeleteModel(
            name='Spot',
        ),
    ]
