# Generated by Django 2.1.9 on 2019-09-25 13:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('spot', models.CharField(max_length=25)),
                ('imagen0', models.ImageField(blank=True, upload_to='img/productos/')),
                ('imagen1', models.ImageField(blank=True, upload_to='img/productos/')),
                ('imagen2', models.ImageField(blank=True, upload_to='img/productos/')),
                ('imagen3', models.ImageField(blank=True, upload_to='img/productos/')),
                ('imagen4', models.ImageField(blank=True, upload_to='img/productos/')),
                ('imagen5', models.ImageField(blank=True, upload_to='img/productos/')),
                ('imagen6', models.ImageField(blank=True, upload_to='img/productos/')),
                ('imagen7', models.ImageField(blank=True, upload_to='img/productos/')),
                ('imagen8', models.ImageField(blank=True, upload_to='img/productos/')),
                ('imagen9', models.ImageField(blank=True, upload_to='img/productos/')),
                ('stock', models.IntegerField(default=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producto', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
