# Generated by Django 2.1.9 on 2019-09-25 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='imagen1',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='imagen2',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='imagen3',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='imagen4',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='imagen5',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='imagen6',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='imagen7',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='imagen8',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='imagen9',
        ),
    ]
