# Generated by Django 2.2.6 on 2019-10-09 13:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0008_auto_20191009_1514'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compra',
            name='comprador',
        ),
        migrations.RemoveField(
            model_name='compra',
            name='vendedor',
        ),
        migrations.AddField(
            model_name='compra',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='compra_u', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='compra',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producto_u', to='home.Producto'),
        ),
    ]
