# Generated by Django 2.1.9 on 2019-10-14 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20191009_1515'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ubicacion',
            options={'verbose_name': 'Ubicacion', 'verbose_name_plural': 'Ubicaciones'},
        ),
        migrations.AlterField(
            model_name='producto',
            name='spot',
            field=models.CharField(choices=[('Europa', 'Europe'), ('Africa', 'Africa'), ('Asia', 'Asia'), ('Oceania', 'Oceania'), ('America del Norte', 'North America'), ('America del Sur', 'South America')], default='Europa', max_length=25),
        ),
    ]
