# Generated by Django 2.1.9 on 2019-10-14 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20191014_1744'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ubicacion',
            name='direccion',
        ),
        migrations.AddField(
            model_name='ubicacion',
            name='spot',
            field=models.CharField(choices=[('Europa', 'Europe'), ('Africa', 'Africa'), ('Asia', 'Asia'), ('Oceania', 'Oceania'), ('America del Norte', 'North America'), ('America del Sur', 'South America')], default='Europa', max_length=25),
        ),
    ]
