# Generated by Django 2.1.9 on 2019-10-18 10:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0016_auto_20191017_1618'),
    ]

    operations = [
        migrations.CreateModel(
            name='Denuncia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.CharField(choices=[('MAL USO', 'Bad usage of the app'), ('INAPROPIADO', 'Innapropiate content'), ('SPAM', 'Spam'), ('OTRO', 'Other')], default='MAL USO', max_length=30)),
                ('detalles', models.CharField(max_length=200)),
                ('emisor', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='denuncia_e', to=settings.AUTH_USER_MODEL)),
                ('receptor', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='denuncia_r', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
