# Generated by Django 2.1.9 on 2019-10-21 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_auto_20191021_1015'),
    ]

    operations = [
        migrations.AddField(
            model_name='ubicacion',
            name='sigla',
            field=models.CharField(default='', max_length=5),
        ),
    ]
