# Generated by Django 2.1.9 on 2019-10-21 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_ubicacion_sigla'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='spot',
            field=models.CharField(choices=[('Europa', 'Europe'), ('Africa', 'Africa'), ('Asia', 'Asia'), ('Oceania', 'Oceania'), ('America del Norte', 'North America'), ('Asia', 'South America')], default='EU', max_length=25),
        ),
        migrations.AlterField(
            model_name='ubicacion',
            name='spot',
            field=models.CharField(choices=[('Europa', 'Europe'), ('Africa', 'Africa'), ('Asia', 'Asia'), ('Oceania', 'Oceania'), ('America del Norte', 'North America'), ('Asia', 'South America')], default='Europa', max_length=25),
        ),
    ]
