# Generated by Django 2.1.9 on 2019-10-23 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_compra_descargas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='descargas',
            field=models.IntegerField(default=3),
        ),
    ]
