# Generated by Django 2.2.6 on 2019-11-05 12:21

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_fs_insert_ubicaciones'),
    ]

    operations = [
        migrations.CreateModel(
            name='Terms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('text', tinymce.models.HTMLField(default='Terminos y condiciones de uso...', help_text='Este es el texto que aparecera en la seccion terminos y condiciones', max_length=15000)),
            ],
            options={
                'verbose_name_plural': 'Terminos y Condiciones',
            },
        ),
    ]
