# Generated by Django 2.2.6 on 2019-11-05 12:59

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_auto_20191105_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privacy',
            name='text',
            field=tinymce.models.HTMLField(default='Politica de privacidad...', help_text='Este es el texto que aparecera en la seccion politica de privacidad', max_length=45000),
        ),
    ]
