# Generated by Django 2.2.6 on 2019-11-06 09:29

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_auto_20191106_1016'),
    ]

    operations = [
        migrations.CreateModel(
            name='Taxes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', tinymce.models.HTMLField(default='Impuestos y facturacion...', help_text='Este es el texto que aparecera en la seccion impuestos y facturacion', max_length=45000)),
                ('text_en', tinymce.models.HTMLField(default='Taxes and billing...', help_text='This is the text that will appear on your taxes & billing section', max_length=45000)),
            ],
            options={
                'verbose_name_plural': 'Impuestos y facturacion',
            },
        ),
        migrations.RemoveField(
            model_name='privacy',
            name='titulo',
        ),
        migrations.RemoveField(
            model_name='terms',
            name='titulo',
        ),
    ]
