# Generated by Django 2.2.6 on 2019-11-06 09:40

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_auto_20191106_1029'),
    ]

    operations = [
        migrations.CreateModel(
            name='FreeSub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', tinymce.models.HTMLField(default='Suscripcion gratuita...', help_text='Este es el texto que aparecera en la seccion suscripcion gratuita', max_length=45000)),
                ('text_en', tinymce.models.HTMLField(default='Free subscription features...', help_text='This is the text that will appear on your free subcription features section', max_length=45000)),
            ],
            options={
                'verbose_name_plural': 'Suscripcion gratuita',
            },
        ),
    ]
