# Generated by Django 2.2.6 on 2019-11-06 09:58

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_freesub'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurePayments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='img/information/')),
                ('text', tinymce.models.HTMLField(default='Seguridad en pagos...', help_text='Este es el texto que aparecera en la seccion seguridad en pagos', max_length=45000)),
                ('text_en', tinymce.models.HTMLField(default='Secure payments...', help_text='This is the text that will appear on your secure payments section', max_length=45000)),
            ],
            options={
                'verbose_name_plural': 'Seguridad en pagos',
            },
        ),
    ]
