# Generated by Django 2.2.6 on 2019-11-06 10:20

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0033_securepayments'),
    ]

    operations = [
        migrations.CreateModel(
            name='Copyright',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', tinymce.models.HTMLField(default='Copyright, licencias y tamaños...', help_text='Este es el texto que aparecera en la seccion copyright, licencias y tamaños', max_length=45000)),
                ('text_en', tinymce.models.HTMLField(default='Copyright, licenses and sizes...', help_text='This is the text that will appear on your copyright, licenses and sizes section', max_length=45000)),
            ],
            options={
                'verbose_name_plural': 'Copyright, licencias y tamaños',
            },
        ),
    ]
