# Generated by Django 2.2.6 on 2019-11-06 10:39

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0034_copyright'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', tinymce.models.HTMLField(default='Instrucciones: vender fotos...', help_text='Este es el texto que aparecera en la seccion instrucciones: vender fotos', max_length=45000)),
                ('text_en', tinymce.models.HTMLField(default='Selling photos: manual...', help_text='This is the text that will appear on your selling photos: manual section', max_length=45000)),
            ],
            options={
                'verbose_name_plural': 'Instrucciones: vender fotos',
            },
        ),
    ]
