# Generated by Django 2.2.6 on 2019-11-07 10:54

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0037_productreturn'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductReturn',
            new_name='Devolucion',
        ),
        migrations.AlterModelOptions(
            name='devolucion',
            options={'verbose_name_plural': 'Devoluciones'},
        ),
    ]
