# Generated by Django 2.2.6 on 2019-11-07 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0039_auto_20191107_1158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devolucion',
            name='order',
        ),
        migrations.AddField(
            model_name='devolucion',
            name='product',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='return_p', to='home.Producto'),
            preserve_default=False,
        ),
    ]
