# Generated by Django 2.2.6 on 2019-11-07 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0040_auto_20191107_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devolucion',
            name='details',
            field=models.TextField(blank=True, max_length=200),
        ),
    ]
