# Generated by Django 2.2.6 on 2019-11-15 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0041_auto_20191107_1446'),
    ]

    operations = [
        migrations.CreateModel(
            name='img_watermark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(blank=True, default=False, help_text='Ten activo solo uno al mismo tiempo')),
                ('imagen', models.ImageField(upload_to='img/watermark/')),
            ],
        ),
    ]
