# Generated by Django 2.2.6 on 2019-11-15 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0042_img_watermark'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='img_watermark',
            new_name='WatermarkImage',
        ),
    ]
