# Generated by Django 2.1.9 on 2020-06-23 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0046_auto_20200420_1712'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='area',
            name='pais',
        ),
        migrations.RemoveField(
            model_name='pais',
            name='continente',
        ),
        migrations.RemoveField(
            model_name='spot',
            name='area',
        ),
        migrations.AlterField(
            model_name='producto',
            name='spot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producto_spot', to='users.Spot'),
        ),
        migrations.DeleteModel(
            name='Area',
        ),
        migrations.DeleteModel(
            name='Continente',
        ),
        migrations.DeleteModel(
            name='Pais',
        ),
        migrations.DeleteModel(
            name='Spot',
        ),
    ]
